version: "3.8"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api-service
    command: npm run start
    ports:
      - 3000:3000

  stocks:
    build:
      dockerfile: Dockerfile
      context: ./stock-service
    command: npm run start
    ports:
      - 3001:3001

